apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: synapsedb
        - name: POSTGRES_USER
          value: synapseuser
        - name: POSTGRES_PASSWORD
          value: synapsepassword
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: LC_COLLATE
          value: "C"
        - name: LC_CTYPE
          value: "C"
        - name: POSTGRES_ENCODING
          value: "UTF8"
        - name: POSTGRES_INITDB_ARGS
          value: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql
        args: ["-D", "/var/lib/postgresql/data/pgdata"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
