# Defining a storage class to use with PVCs for Azure Disk with Retain reclaim policy
# Data will be retained even after the PVC is deleted
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-retained
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: Retain
volumeBindingMode: Immediate
