apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-retained
  resources:
    requests:
      storage: 5Gi
