apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      volumes:
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-pvc
        - name: synapse-config
          configMap:
            name: synapse-config
      containers:
      - name: synapse
        image: matrixdotorg/synapse:latest
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        volumeMounts:
        - name: synapse-data
          mountPath: /data
        - name: synapse-config
          mountPath: /config
        env:
        - name: SYNAPSE_CONFIG_PATH
          value: "/config/homeserver.yaml"
        ports:
        - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
