apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      initContainers:
        - name: fix-perms
          image: alpine
          command: ['sh', '-c', 'chown -R 991:991 /data && chmod -R 700 /data']
          volumeMounts:
            - name: synapse-data
              mountPath: /data
      volumes:
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-pvc
        - name: synapse-config
          configMap:
            name: synapse-config
      containers:
        - name: synapse
          image: matrixdotorg/synapse:latest
          securityContext:
            runAsUser: 991
            runAsGroup: 991
          volumeMounts:
            - name: synapse-data
              mountPath: /data
            - name: synapse-config
              mountPath: /config
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: "/config/homeserver.yaml"
            - name: SYNAPSE_SERVER_NAME
              value: "synapse.okonech.net"
            - name: SYNAPSE_REPORT_STATS
              value: "no"
            - name: POSTGRES_DB
              value: synapsedb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_HOST
              value: "postgres"
          ports:
            - containerPort: 8008
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: synapse
spec:
  type: ClusterIP
  selector:
    app: synapse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8008

